Vue.component('local-download', {
  props: {
    canpack: Boolean,
  },
  template: 
    '<div>\
      <button id="DownloadLocally" :disabled="canDownloadLocally" class="btn btn-block btn-custom" v-on:click="downloadLocally">Download locally (ALPHA)</button>\
      <div id="downloadModal" v-show="modalOpened">\
        <div id="downloadModalContent" class="p-3">\
          <button id="close" type="button" :disabled="canCloseModal" v-on:click="modalOpened = false" class="close" aria-label="Close">\
            <span aria-hidden="true">&times;</span>\
          </button>\
          <div id="steps" class="row">\
            <div v-for="(step, index) in steps" :key="step.name" class="col text-center">\
              <div v-if="index == currentStep" class="mx-auto btn btn-custom">{{ index+1 }}</div>\
              <div v-else disabled class="mx-auto btn btn-custom">{{ index+1 }}</div>\
            </div>\
          </div>\
          <h3 class="my-3">{{ steps[currentStep].name }}</h3>\
          <p v-if="currentStep < 2">{{ steps[currentStep].content + currentMod.name + " v" + currentMod.version }}</p>\
          <p v-else>{{ steps[currentStep].content }}</p>\
          <div id="logs">\
            <div v-for="(log, index) in logs" :key="index" :class="{ log: true, error: log.type === "error" }">{{ log.value }}</div>\
          </div>\
        </div><span class="taille"></span>\
      </div>\
    </div>',
  data() {
    return {
      dbName: 'faithful',
      dbVersion: 2.0,
      database: null,
      isDownloading: false,
      store: null,
      stores: [
        {
          name: 'files',
          options: { autoIncrement: true }
        }
      ],
      steps: [
        {
          name: 'Downloading mods',
          content: 'Downloading '
        },
        {
          name: 'Unzipping mods',
          content: 'Extracting '
        },
        {
          name: 'Creating archive',
          content: 'Zipping...'
        }
      ],
      currentStep: 0,
      currentMod: '',
      modalOpened: false,
      logs: []
    }
  },
  methods: {
    downloadMod: function(mod) {
      this.currentMod = mod
      this.logStep()
      return axios({
        url:
          "https://api.allorigins.win/raw?url=https://github.com/" + "Faithful-Mods" + "/" + mod.name + "/archive/" + mod.version + ".zip",
        method: "GET",
        responseType: "blob" // important
      })
    },
    downloadLocally: function() {
      const finalZip = new JSZip()

      this.isDownloading = true
      this.modalOpened = true

      const modSelection = this.$root.modSelection

      const promises = []
      modSelection.forEach(mod => {
        promises.push(this.downloadMod(mod))
      })
      
      this.currentStep = 0

      let success = 0
      Promise.all(promises).then((values) => {
        this.currentStep = 1
        values.forEach((res, index) => {
          this.currentMod = modSelection[index]
          this.logStep()
          const fileKey = modSelection[index].name + '-' + modSelection[index].version

          this.store.delete(fileKey).then(() => {
            return this.store.put(res.data, fileKey)
          })
          .then(() => {
            let zip = new JSZip()
            return zip.loadAsync(res.data)
          })
          .then((zip) => {
            const keys = Object.keys(zip.files)
          
            let newName
            for(let i = 0; i < keys.length; ++i) {
              newName = keys[i].replace(fileKey + '/', '')
              
              if(newName.trim() !== '') {
                finalZip.files[newName] = zip.files[keys[i]]
                finalZip.files[newName].name = newName
              }
            }

            ++success
            // if all archives have been successfully added
            if(success == modSelection.length) {
              this.currentStep = 2
              this.logStep()
              finalZip.generateAsync({
                type:"blob",
                comment: "Resource pack generated by Faithful Mods",
                compression: "DEFLATE",
                compressionOptions: {
                  level: 9
                }
              }).then(blob => {            // 1) generate the zip file
                  saveAs(blob, 'Faithful Mods Resource Pack ' + ((new Date).getTime()) + ".zip") // 2) trigger the download
                  this.isDownloading = false
              }, err => {
                  console.error(err)
                  this.isDownloading = false
              });
            }
          }).catch(err => {
            console.error(err)
            this.isDownloading = false
          })
        })
      }).catch(reason => {
        console.error(reason)
        this.isDownloading = false
      })
    },
    addLog: function(value, isError = false) {
      this.logs.push({
        type: isError ? 'error' : 'log',
        value: '' + value
      })
    },
    logStep: function() {
      if(this.currentStep < this.steps.length - 1) {
        this.addLog(this.steps[this.currentStep].content + this.currentMod.name + " v" + this.currentMod.version)
      } else {
        this.addLog(this.steps[this.currentStep].content)
      }
    },
    log: function(obj) {
      this.addLog(obj)
    },
    error: function(err) {
      this.addLog(err, true)
      console.error(err)
    }
  },
  computed: {
    canDownloadLocally: function() {
      return !this.$props.canpack || this.isDownloading || !this.database || !this.store
    },
    canCloseModal: function() {
      return this.modalOpened && !this.isDownloading
    }
  },
  mounted: function() {  
    IndexedDBPromise.open(this.dbName, this.dbVersion, this.stores)
    .then((db) => {
      this.database = db
      return db.getStore(this.stores[0].name, 'readwrite', true)
    })
    .then((store) => {
      this.store = store
    })
  }
})